swagger: "2.0"
info:
  title: SSP BOT API
  description: SSP BOT API
  version: 1.0.0
host: ssp.bot.api
schemes:
  - https
  - http
paths:
  /round/call:
    post:
      summary: Call player to play.
      description: SSP Server calls player to play.
      produces:
        - application/json
      responses:
        200:
          description: OK


definitions:


